export const teams = [
  {
    id: 1,
    abbreviation: "ATL",
    city: "Atlanta",
    conference: "East",
    division: "Southeast",
    full_name: "Atlanta Hawks",
    name: "Hawks",
    colors: {
      color_1: "#E03A3E",
      color_2: "#C1D32F",
      color_3: "#26282A",
      color_4: null,
      color_5: null,
    },
  },
  {
    id: 2,
    abbreviation: "BOS",
    city: "Boston",
    conference: "East",
    division: "Atlantic",
    full_name: "Boston Celtics",
    name: "Celtics",
    colors: {
      color_1: "#007A33",
      color_2: "#963821",
      color_3: "#BA9653",
      color_4: null,
      color_5: null,
    },
  },
  {
    id: 3,
    abbreviation: "BKN",
    city: "Brooklyn",
    conference: "East",
    division: "Atlantic",
    full_name: "Brooklyn Nets",
    name: "Nets",
    colors: {
      color_1: "#000000",
      color_2: "#FFFFFF",
      color_3: null,
      color_4: null,
      color_5: null,
    },
  },
  {
    id: 4,
    abbreviation: "CHA",
    city: "Charlotte",
    conference: "East",
    division: "Southeast",
    full_name: "Charlotte Hornets",
    name: "Hornets",
    colors: {
      color_1: "#1D1160",
      color_2: "#00788C",
      color_3: "#A1A1A4",
      color_4: null,
      color_5: null,
    },
  },
  {
    id: 5,
    abbreviation: "CHI",
    city: "Chicago",
    conference: "East",
    division: "Central",
    full_name: "Chicago Bulls",
    name: "Bulls",
    colors: {
      color_1: "#CE1141",
      color_2: "#000000",
      color_3: null,
      color_4: null,
      color_5: null,
    },
  },
  {
    id: 6,
    abbreviation: "CLE",
    city: "Cleveland",
    conference: "East",
    division: "Central",
    full_name: "Cleveland Cavaliers",
    name: "Cavaliers",
    colors: {
      color_1: "#860038",
      color_2: "#041E42",
      color_3: "#26282A",
      color_4: "#000000",
      color_5: null,
    },
  },
  {
    id: 7,
    abbreviation: "DAL",
    city: "Dallas",
    conference: "West",
    division: "Southwest",
    full_name: "Dallas Mavericks",
    name: "Mavericks",
    colors: {
      color_1: "#00538C",
      color_2: "#002B5E",
      color_3: "#B8C4CA",
      color_4: "#000000",
      color_5: null,
    },
  },
  {
    id: 8,
    abbreviation: "DEN",
    city: "Denver",
    conference: "West",
    division: "Northwest",
    full_name: "Denver Nuggets",
    name: "Nuggets",
    colors: {
      color_1: "#0E2240",
      color_2: "#FEC524",
      color_3: "#8B2131",
      color_4: "#1D428A",
      color_5: null,
    },
  },
  {
    id: 9,
    abbreviation: "DET",
    city: "Detroit",
    conference: "East",
    division: "Central",
    full_name: "Detroit Pistons",
    name: "Pistons",
    colors: {
      color_1: "#C8102E",
      color_2: "#1D42BA",
      color_3: "#BEC0C2",
      color_4: "#002D62",
      color_5: null,
    },
  },
  {
    id: 10,
    abbreviation: "GSW",
    city: "Golden State",
    conference: "West",
    division: "Pacific",
    full_name: "Golden State Warriors",
    name: "Warriors",
    colors: {
      color_1: "#1D428A",
      color_2: "#FFC72C",
      color_3: null,
      color_4: null,
      color_5: null,
    },
  },
  {
    id: 11,
    abbreviation: "HOU",
    city: "Houston",
    conference: "West",
    division: "Southwest",
    full_name: "Houston Rockets",
    name: "Rockets",
    colors: {
      color_1: "#CE1141",
      color_2: "#000000",
      color_3: "#C4CED4",
      color_4: null,
      color_5: null,
    },
  },
  {
    id: 12,
    abbreviation: "IND",
    city: "Indiana",
    conference: "East",
    division: "Central",
    full_name: "Indiana Pacers",
    name: "Pacers",
    colors: {
      color_1: "#002D62",
      color_2: "#FDBB30",
      color_3: "#BEC0C2",
      color_4: null,
      color_5: null,
    },
  },
  {
    id: 13,
    abbreviation: "LAC",
    city: "Los Angeles",
    conference: "West",
    division: "Pacific",
    full_name: "Los Angeles Clippers",
    name: "Clippers",
    colors: {
      color_1: "#C8102E",
      color_2: "#1D428A",
      color_3: "#BEC0C2",
      color_4: "#000000",
      color_5: null,
    },
  },
  {
    id: 14,
    abbreviation: "LAL",
    city: "Los Angeles",
    conference: "West",
    division: "Pacific",
    full_name: "Los Angeles Lakers",
    name: "Lakers",
    colors: {
      color_1: "#552583",
      color_2: "#FDB927",
      color_3: "#000000",
      color_4: null,
      color_5: null,
    },
  },
  {
    id: 15,
    abbreviation: "MEM",
    city: "Memphis",
    conference: "West",
    division: "Southwest",
    full_name: "Memphis Grizzlies",
    name: "Grizzlies",
    colors: {
      color_1: "#5D76A9",
      color_2: "#12173F",
      color_3: "#F5B112",
      color_4: "#707271",
      color_5: null,
    },
  },
  {
    id: 16,
    abbreviation: "MIA",
    city: "Miami",
    conference: "East",
    division: "Southeast",
    full_name: "Miami Heat",
    name: "Heat",
    colors: {
      color_1: "#98002E",
      color_2: "#F9A01B",
      color_3: "#000000",
      color_4: null,
      color_5: null,
    },
  },
  {
    id: 17,
    abbreviation: "MIL",
    city: "Milwaukee",
    conference: "East",
    division: "Central",
    full_name: "Milwaukee Bucks",
    name: "Bucks",
    colors: {
      color_1: "#00471B",
      color_2: "#EEE1C6",
      color_3: "#0077C0",
      color_4: "#000000",
      color_5: null,
    },
  },
  {
    id: 18,
    abbreviation: "MIN",
    city: "Minnesota",
    conference: "West",
    division: "Northwest",
    full_name: "Minnesota Timberwolves",
    name: "Timberwolves",
    colors: {
      color_1: "#0C2340",
      color_2: "#236192",
      color_3: "#9EA2A2",
      color_4: "#78BE20",
      color_5: null,
    },
  },
  {
    id: 19,
    abbreviation: "NOP",
    city: "New Orleans",
    conference: "West",
    division: "Southwest",
    full_name: "New Orleans Pelicans",
    name: "Pelicans",
    colors: {
      color_1: "#0C2340",
      color_2: "#C8102E",
      color_3: "#85714D",
      color_4: null,
      color_5: null,
    },
  },
  {
    id: 20,
    abbreviation: "NYK",
    city: "New York",
    conference: "East",
    division: "Atlantic",
    full_name: "New York Knicks",
    name: "Knicks",
    colors: {
      color_1: "#006BB6",
      color_2: "#F58426",
      color_3: "#BEC0C2",
      color_4: "#000000",
      color_5: null,
    },
  },
  {
    id: 21,
    abbreviation: "OKC",
    city: "Oklahoma City",
    conference: "West",
    division: "Northwest",
    full_name: "Oklahoma City Thunder",
    name: "Thunder",
    colors: {
      color_1: "#007AC1",
      color_2: "#EF3B24",
      color_3: "#002D62",
      color_4: "#FDBB30",
      color_5: null,
    },
  },
  {
    id: 22,
    abbreviation: "ORL",
    city: "Orlando",
    conference: "East",
    division: "Southeast",
    full_name: "Orlando Magic",
    name: "Magic",
    colors: {
      color_1: "#0077C0",
      color_2: "#C4CED4",
      color_3: "#000000",
      color_4: null,
      color_5: null,
    },
  },
  {
    id: 23,
    abbreviation: "PHI",
    city: "Philadelphia",
    conference: "East",
    division: "Atlantic",
    full_name: "Philadelphia 76ers",
    name: "76ers",
    colors: {
      color_1: "#006BB6",
      color_2: "#ED174C",
      color_3: "#002B5C",
      color_4: "#C4CED4",
      color_5: null,
    },
  },
  {
    id: 24,
    abbreviation: "PHX",
    city: "Phoenix",
    conference: "West",
    division: "Pacific",
    full_name: "Phoenix Suns",
    name: "Suns",
    colors: {
      color_1: "#1D1160",
      color_2: "#E56020",
      color_3: "#000000",
      color_4: "#63727A",
      color_5: "#F9AD1B",
    },
  },
  {
    id: 25,
    abbreviation: "POR",
    city: "Portland",
    conference: "West",
    division: "Northwest",
    full_name: "Portland Trail Blazers",
    name: "Trail Blazers",
    colors: {
      color_1: "#E03A3E",
      color_2: "#000000",
      color_3: null,
      color_4: null,
      color_5: null,
    },
  },
  {
    id: 26,
    abbreviation: "SAC",
    city: "Sacramento",
    conference: "West",
    division: "Pacific",
    full_name: "Sacramento Kings",
    name: "Kings",
    colors: {
      color_1: "#5A2D81",
      color_2: "#63727A",
      color_3: "#000000",
      color_4: null,
      color_5: null,
    },
  },
  {
    id: 27,
    abbreviation: "SAS",
    city: "San Antonio",
    conference: "West",
    division: "Southwest",
    full_name: "San Antonio Spurs",
    name: "Spurs",
    colors: {
      color_1: "#C4CED4",
      color_2: "#000000",
      color_3: null,
      color_4: null,
      color_5: null,
    },
  },
  {
    id: 28,
    abbreviation: "TOR",
    city: "Toronto",
    conference: "East",
    division: "Atlantic",
    full_name: "Toronto Raptors",
    name: "Raptors",
    colors: {
      color_1: "#CE1141",
      color_2: "#000000",
      color_3: "#A1A1A4",
      color_4: "#B4975A",
      color_5: null,
    },
  },
  {
    id: 29,
    abbreviation: "UTA",
    city: "Utah",
    conference: "West",
    division: "Northwest",
    full_name: "Utah Jazz",
    name: "Jazz",
    colors: {
      color_1: "#002B5C",
      color_2: "#00471B",
      color_3: "#F9A01B",
      color_4: null,
      color_5: null,
    },
  },
  {
    id: 30,
    abbreviation: "WAS",
    city: "Washington",
    conference: "East",
    division: "Southeast",
    full_name: "Washington Wizards",
    name: "Wizards",
    colors: {
      color_1: "#002B5C",
      color_2: "#E31837",
      color_3: "#C4CED4",
      color_4: null,
      color_5: null,
    },
  },
];
